apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-apache-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-apache
    spec:
      containers:
      - name: my-apache-container1
        image: httpd
        ports:
        -  containerPort: 80
